### ISSUE TITLE
Error running command

### ISSUE THREAD

**Issue by klunghamer** [Qualys-Public/AWS_Cloud_Agent_SSM#1]
Any idea the source of the below error. Running on Amazon linux 2. Thanks!

----------ERROR-------

Redirecting to /bin/systemctl status qualys-cloud-agent.service

Unit qualys-cloud-agent.service could not be found.

failed to run commands: exit status 4

**Comment by mkhanal1** [comment]
The issue arises when the installation path specified for Cloud Agent ($INSTALLER_FILE_URL) is either empty or not a valid one.
